### ISSUE TITLE
Suggestion: use snapshot testing

### ISSUE THREAD

**Issue by JaKXz** [bcoe/v8-to-istanbul#1]
This would definitely be better served with some snapshot testing library:

https://github.com/bcoe/v8-to-istanbul/blob/1db19cf76536467012a762f0d202e551f17a07e1/test/utils/run-fixture.js#L20-L24

`jest` is not the only answer so we can maintain the integration test using nyc, if you want to: 

https://github.com/bahmutov/snap-shot
https://www.npmjs.com/package/chai-jest-snapshot
https://www.npmjs.com/package/mocha-snapshots

**Comment by bcoe** [comment]
@JaKXz `node-tap` also recently introduced snapshotting, and I know @isaacs would love to have some testers; any chance I could entice you into working on this? I'm somewhat new to this concept, so would love to have an introduction to the workflow.

**Comment by JaKXz** [comment]
Sure! I'll take a look at node-tap :)

**Comment by isaacs** [comment]
tap basics: http://www.node-tap.org/basics/
snapshots in tap: http://www.node-tap.org/snapshots/

**Comment by JaKXz** [comment]
@isaacs glad I caught you: I tried using the `TAP_SNAPSHOTS=1 tap test/*.js` command and snapshot files are not being written to the `tap-snapshots` folder (see https://github.com/bcoe/v8-to-istanbul/commit/0e42299de59f8f1890a9362a32cc80a065a3289d). I think it's because of the test setup in this project

**Comment by isaacs** [comment]
I notice on this line that it only does the assertion if `process.env.DEBUG === true` on https://github.com/bcoe/v8-to-istanbul/commit/0e42299de59f8f1890a9362a32cc80a065a3289d#diff-1e2e8cb018d1180d972ec55f27252b59R21

Is that set?  If not, it wouldn't hit the `t.matchSnapshot()` call.

Also, I recommend _not_ setting `TAP_SNAPSHOT=1` in your test script here: https://github.com/bcoe/v8-to-istanbul/commit/0e42299de59f8f1890a9362a32cc80a065a3289d#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R7

It'd be better to do something like:

```json
  "scripts": {
    "test": "tap test/*.js --cov",
    "snapshot": "TAP_SNAPSHOT=1 npm test"
  }
```

Otherwise, you won't see test failures, they'll just be rewritten to the snapshot file every time.

**Comment by JaKXz** [comment]
My bad, I got tunnelvision'd. Thanks again!
